Modules/Order/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Modules\Order\Http\Controllers\OrderController;


Route::prefix('order')->group(function() {
    Route::get('/', 'OrderController@index');
});



Route::middleware('auth')->resource('order', OrderController::class);


// Define the route without CSRF protection
Route::match(['post', 'get'], '/callback', function (Request $request) {
    // Handle both POST and GET requests here
    if ($request->isMethod('post')) {
        // Handle POST request
        dd($request->all());
    } else {
        // Handle GET request
        dd($request->all());
    }
})->withoutMiddleware(['web', 'csrf']);

Modules/Order/Entities/Item.php
<?php

namespace Modules\Order\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Order\Entities\Order; // Assuming there's an Order model

class Item extends Model
{
    protected $fillable = ['product_name', 'quantity', 'price'];

    /**
     * Get the orders that belong to this item.
     */
    public function orders()
    {
        return $this->belongsToMany(Order::class)->withPivot('quantity', 'price')->withTimestamps();
    }

    // Add any other relationships as needed
}

Modules/Order/Entities/Order.php
<?php

namespace Modules\Order\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Payment\Entities\PaymentTransaction;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Order.
 *
 * @package namespace App\Entities;
 */
class Order extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['description', 'address','bank_number', 'total_price', 'status', 'user_id'];


    /**
     * Get the items for the order.
     */
    public function items()
    {
        return $this->belongsToMany(Item::class)->withPivot('quantity', 'price')->withTimestamps();
    }

    public function paymentTransactions()
    {
        return $this->hasMany(PaymentTransaction::class);
    }

    // Your existing code...

    /**
     * Mark the order as paid.
     *
     * @return bool
     */
    public function markAsPaid()
    {
        $this->status = "Settled";
        return $this->save();
    }
}

Modules/Order/Http/Controllers/Api/OrderController.php
<?php

namespace Modules\Order\Http\Controllers\Api;

use Illuminate\Http\Request;
use Modules\Order\Entities\Order;
use Modules\Order\Http\Resources\OrderResource;
use Modules\Order\Repositories\OrderRepository;

class OrderController
{
    protected $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }
    public function index()
    {
        $orders = Order::all();
        return OrderResource::collection($orders);
    }

    public function store(Request $request)
    {
        // Get the authenticated user
        $user = auth()->user();

        // Check if a user is authenticated
        if ($user) {
            // Use the authenticated user's ID
            $userId = $user->id;
        } else {
            // If no user is authenticated, set the user ID to null or handle the case as needed
            $userId = null;
        }

        // Call the repository method to create the order
        $order = $this->orderRepository->createOrderWithItems($request->all(), $userId);

        // Return a JSON response indicating success
        return new OrderResource($order);
    }

    public function show($id)
    {
        $order = Order::find($id);
        return new OrderResource($order);
    }
}

Modules/Order/Http/Controllers/OrderController.php
<?php

// app/Http/Controllers/OrderController.php

namespace Modules\Order\Http\Controllers;

use Illuminate\Http\Request;
use Modules\Order\Entities\Item;
use Modules\Order\Entities\Order;
use Modules\Order\Http\Requests\OrderRequest;
use Modules\Order\Repositories\OrderRepository;

class OrderController
{
    protected $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    public function create()
    {

         $items =Item::all();
        return view('order::create',compact('items'));
    }

    public function store(OrderRequest $request)
    {

        $user = auth()->user();
       $order =  $this->orderRepository->createOrderWithItems($request->all(), $user->id);

        return redirect()->route("order.show", ['order' => $order->id])->with('success', 'The order created successfully');

    }

    public function Show(string $id)
    {
    $order = Order::find($id);

        return view('order::show',compact('order'));
    }
}

Modules/Order/Resources/views/create.blade.php
@extends('layout.admin')
@section('title', 'سفارشات ')

@section('body')

    <div class="content-wrapper" style="min-height: 845px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="row-cols-sm-6">
                        <h1>@yield('title')</h1>
                    </div>
                </div><!-- /.container-fluid -->
            </div>
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    @if ($errors->any())
                        <div class="col-md-12">
                            <div class="alert alert-danger">
                                <strong>خطا!</strong> لطفاً خطاهای زیر را اصلاح کنید:<br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif
                </div>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="ion ion-clipboard mr-1"></i>
                            محصولات
                        </h3>

                        <div class="card-tools">
                            <ul class="pagination pagination-sm">
                                <li class="page-item"><a href="#" class="page-link">&laquo;</a></li>
                                <li class="page-item"><a href="#" class="page-link">1</a></li>
                                <li class="page-item"><a href="#" class="page-link">2</a></li>
                                <li class="page-item"><a href="#" class="page-link">3</a></li>
                                <li class="page-item"><a href="#" class="page-link">&raquo;</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <!-- Replace the following card sections with your desired content -->
                        @foreach($items as $item)
                            <div class="col-md-4">
                                <div class="card card-primary card-outline">
                                    <div class="card-body box-profile">
                                        <h3 class="profile-username text-center">{{ $item['product_name'] }}</h3>
                                        <p class="text-muted text-center">تعداد: {{ $item['quantity'] }}</p>
                                        <ul class="list-group list-group-unbordered mb-3">
                                            <li class="list-group-item">
                                                <b>قیمت</b> <span class="float-right">{{ $item['price'] }}</span>
                                            </li>
                                            <!-- Add more details here if needed -->
                                        </ul>
                                        <button type="button" class="btn btn-outline-info btn-block" data-toggle="modal" data-target="#exampleModal{{ $loop->index }}"><b>انتخاب</b></button>
                                    </div>
                                </div>
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal{{ $loop->index }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">اطلاعات پرداخت</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <!-- Add your form fields for address and bank number here -->
                                                <form action="{{ route('order.store') }}" method="POST">
                                                    @csrf
                                                    <div class="form-group">
                                                        <label for="address">آدرس:</label>
                                                        <textarea class="form-control" id="address" name="order[address]" rows="3" placeholder="آدرس را وارد کنید"></textarea>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="bank_number">شماره کارت:</label>
                                                        <input type="text" class="form-control" id="bank_number" name="order[bank_number]" placeholder="شماره کارت را وارد کنید">
                                                    </div>
                                                    <!-- Hidden input fields for order data -->
                                                    <input type="hidden" name="order[description]" value="Order description">
                                                    <input type="hidden" name="order[done_at]" value="{{ now()->toDateString() }}">
                                                    <input type="hidden" name="items_ids[{{ $loop->index }}][]" value="{{ $item['id'] }}">
                                                    <input type="hidden" name="total_price" value="{{ $item['price'] }}">
{{--                                                    <input type="hidden" name="order_id" value="{{ $order->id }}">--}}
                                                    <button type="submit" class="btn btn-success"><i class="fa fa-credit-card"></i> ثبت سفارش</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </section>
    </div>
    @include('layout.js')
    @yield('js')
    </body>
    </html>

Modules/Order/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Module Order</title>

       {{-- Laravel Mix - CSS File --}}
       {{-- <link rel="stylesheet" href="{{ mix('css/order.css') }}"> --}}

    </head>
    <body>
        @yield('content')

        {{-- Laravel Mix - JS File --}}
        {{-- <script src="{{ mix('js/order.js') }}"></script> --}}
    </body>
</html>

Modules/Order/Resources/views/show.blade.php
@extends('layout.admin')
@section('title', 'صورتحساب')

@section('body')

    <div class="content-wrapper" style="min-height: 845px;">
        @if(session()->has('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif

        @if ($errors->any())
            <div class="col-md-12">
                <div class="alert alert-danger">
                    <strong>خطا!</strong> لطفاً خطاهای زیر را اصلاح کنید:<br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>صورتحساب</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-left">
                            <li class="breadcrumb-item"><a href="#">خانه</a></li>
                            <li class="breadcrumb-item active">صورتحساب</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <!-- Main content -->
                        <div class="invoice p-3 mb-3">
                            <!-- info row -->
                            <div class="row invoice-info">
                                <div class="col-sm-4 invoice-col">
                                    <strong>از:</strong>
                                    <address>
                                        <!-- Your address details here -->
                                    </address>
                                </div>
                                <div class="col-sm-4 invoice-col">
                                    <strong>به:</strong>
                                    <address>
                                        <!-- Recipient's address details here -->
                                    </address>
                                </div>
                            </div><!-- /.row -->

                            <!-- Table row -->
                            <div class="row">
                                <div class="col-12 table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>قیمت کل</th>
                                            <th>ادرس</th>
                                            <th>وضعیت</th>
{{--                                            <th>توضیحات</th>--}}

                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>

                                            <td>{{ $order->total_price ?? '' }}</td>

                                            <td>{{ $order->address ?? '' }}</td>

                                            <td>{{ $order->status ?? '' }}</td>
{{--                                            <td>{{ $order->desciption ?? '' }}</td>--}}
                                            <!-- Add more rows as needed -->
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div><!-- /.row -->

                            <!-- Invoice total row -->
                            <div class="row">
                                <div class="col-12">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <tbody>
                                            <tr>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div><!-- /.row -->

                            <!-- Print and payment buttons -->
                            <div class="row no-print">
                                <div class="col-12">
                                    <button onclick="window.print()" target="_blank" class="btn btn-default">
                                        <i class="fa fa-print"></i> پرینت
                                    </button>
                                    <form id="paymentForm" action="{{ route('payment') }}" method="POST">
                                        @csrf
                                        <input type="hidden" name="total_price" value="{{ $order->total_price }}">
                                        <input type="hidden" name="order_id" value="{{ $order->id }}">
                                        <button type="submit" class="btn btn-success float-left">
                                            <i class="fa fa-credit-card"></i> پرداخت صورتحساب
                                        </button>
                                    </form>
                                    <button type="button" class="btn btn-primary float-left ml-2">
                                        <i class="fa fa-download"></i> تولید PDF
                                    </button>
                                </div>
                            </div><!-- /.row -->
                        </div><!-- /.invoice -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

@endsection

@section('js')
    <!-- Custom JS code goes here -->
@endsection